[project]
name = "mlx-a2a"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "huggingface_hub[cli]",
    "mlx",
    "mlx-lm",
    "transformers",
]

[project.scripts]
convert = "mlx_a2a.convert:main"
